name:                Jasskell
version:             0.1.0.0
github:              "ambroslins/Jasskell"
license:             BSD3
author:              "Ambros Lins"
maintainer:          "ambros.lins@gmail.com"
copyright:           "2020 Ambros Lins"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Jasskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- finite-typelits
- vector-sized

library:
  source-dirs: src

executables:
  Jasskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Jasskell

tests:
  Jasskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Jasskell
